# Generated by Django 4.2.4 on 2024-05-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toyFactory', '0001_initial'),
    ]

    operations = [
    ]
