# Generated by Django 4.2.4 on 2024-05-22 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyFactory', '0002_alter_order_delivery_date_alter_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 25, 16, 39, 7, 255187, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(verbose_name=847200),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.IntegerField(default=86891),
        ),
    ]
