# Generated by Django 4.2.4 on 2024-10-27 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyFactory', '0003_dictionaryofterms_alter_order_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='text',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='certificate',
            field=models.TextField(blank=True, null=True, verbose_name='Сертификаты'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='description',
            field=models.TextField(default='', verbose_name='Описание компании'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='История по годам'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип компании'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(blank=True, null=True, verbose_name='Реквизиты'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Видео о компании'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 0, 59, 5, 708690, tzinfo=datetime.timezone.utc)),
        ),
    ]
