# Generated by Django 4.2.4 on 2024-05-18 23:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyFactory', '0003_alter_order_deliverydate_alter_purchase_purchase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliverydate',
            field=models.DateField(default=datetime.datetime(2024, 5, 21, 23, 16, 46, 665836, tzinfo=datetime.timezone.utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 5, 21, 23, 16, 46, 665858, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.IntegerField(default=16522),
        ),
    ]
