# Generated by Django 4.2.4 on 2024-05-18 23:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyFactory', '0006_alter_order_deliverydate_alter_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliverydate',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 21, 23, 17, 53, 315040, tzinfo=datetime.timezone.utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 5, 21, 23, 17, 53, 315051, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.IntegerField(default=69023),
        ),
    ]
