# Generated by Django 4.2.4 on 2024-05-18 23:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyFactory', '0007_remove_order_deliverydate_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 21, 23, 18, 2, 380292, tzinfo=datetime.timezone.utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 5, 21, 23, 18, 2, 380305, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.IntegerField(default=91166),
        ),
    ]
