# Generated by Django 4.2.4 on 2024-05-19 12:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyFactory', '0008_alter_order_delivery_date_alter_purchase_purchase_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='role',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 22, 12, 41, 14, 435099, tzinfo=datetime.timezone.utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 5, 22, 12, 41, 14, 435110, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.IntegerField(default=69895),
        ),
    ]
