# Generated by Django 4.2.4 on 2024-05-19 13:04

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyFactory', '0009_rename_role_order_status_alter_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 22, 13, 4, 45, 881086, tzinfo=datetime.timezone.utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 5, 22, 13, 4, 45, 881099, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.IntegerField(default=85881),
        ),
    ]
